trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureContainerApps@1
    inputs:
      azureSubscription: "my-service-connection"
      containerAppName: "capps-devops-demo-app"
      resourceGroup: "capps-demo-rg"
      imageToDeploy: "mcr.microsoft.com/k8se/quickstart:latest"
